name = "SentryIntegration"
uuid = "0c0dc41a-7892-49ef-a372-46007ef8f0a8"
authors = ["Daniel Cocks <daniel.cocks@gmail.com>"]
version = "0.3.3"

[deps]
AutoParameters = "2688778c-3549-4980-b6fe-7a9ff5c92ab2"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PkgVersion = "eebad327-c553-4316-9ea0-9fa01ccd7688"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
